package com.weather;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Map;

import com.weather.security.JwtService;
import com.weather.support.ApiClient;
import com.weather.support.ApiClient.Result;
import com.weather.support.IntegrationTestSupport;
import com.weather.support.StubUpstreams;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.env.Environment;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.postgresql.PostgreSQLContainer;

/**
 * Starts the Java API on a database created by the Node/Prisma backend (original migration SQL plus
 * rows, password hash and JWTs produced by the Node libraries) and checks that nothing is lost.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class LegacyDatabaseCompatibilityTest {

  private static final String USER_ID = "cm0legacyuser000000000001";
  private static final String EMAIL = "legacy@example.com";
  /** bcryptjs.hash("Password123!", 12) generated by the Node backend's library. */
  private static final String BCRYPTJS_HASH = "$2b$12$iQQAomKDnzjbGDg5DNWvAePRpUc7s9lFL.jgHy4WyTbIKAAFQ/ogm";
  /** jsonwebtoken.sign({ sub, email, type: "access" }, ACCESS_SECRET) from the Node backend. */
  private static final String NODE_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTBsZWdhY3l1c2VyMDAwMDAwMDAwMDAxIiwiZW1haWwiOiJsZWdhY3lAZXhhbXBsZS5jb20iLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzkwNTMyMjIzLCJleHAiOjQ5NDYyOTIyMjN9.SLvNVRhQ0aEvLvA6LdiYPw0-IsRlUr8DodjQpdGvk_0";
  private static final String NODE_EXPIRED_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTBsZWdhY3l1c2VyMDAwMDAwMDAwMDAxIiwiZW1haWwiOiJsZWdhY3lAZXhhbXBsZS5jb20iLCJ0eXBlIjoiYWNjZXNzIiwiaWF0IjoxNzkwNTMyMjIzLCJleHAiOjE3OTA1MzIyMTN9.w4dGqQ6zhBGPe8L8YUsltnI6xFX-Han3TcsLilTc6Ww";
  /** jsonwebtoken.sign({ sub, jti, type: "refresh" }, REFRESH_SECRET) from the Node backend. */
  private static final String NODE_REFRESH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbTBsZWdhY3l1c2VyMDAwMDAwMDAwMDAxIiwianRpIjoiN2Q2ZjNhNTItM2MxZS00ZjdlLTlkMWEtMmI4YzllMGYxYTIzIiwidHlwZSI6InJlZnJlc2giLCJpYXQiOjE3OTA1MzIyMjMsImV4cCI6NDk0NjI5MjIyM30.jtz1dJJPpkuUJUPscsQs7q1m7jajQbXM1w0j_sN1Pz4";
  private static final String REFRESH_JTI = "7d6f3a52-3c1e-4f7e-9d1a-2b8c9e0f1a23";

  private static final PostgreSQLContainer POSTGRES = new PostgreSQLContainer("postgres:17-alpine")
      .withDatabaseName("legacy")
      .withUsername("legacy")
      .withPassword("legacy");

  static {
    POSTGRES.start();
    seedPrismaDatabase();
  }

  @Autowired
  private Environment environment;

  private ApiClient api;

  @DynamicPropertySource
  static void properties(DynamicPropertyRegistry registry) {
    IntegrationTestSupport.registerCommon(registry, POSTGRES);
  }

  @BeforeEach
  void createClient() {
    api = new ApiClient(environment.getRequiredProperty("local.server.port", Integer.class));
  }

  private static void seedPrismaDatabase() {
    try (Connection connection = connect(); Statement statement = connection.createStatement()) {
      statement.execute("""
          CREATE TABLE "_prisma_migrations" (
            "id" VARCHAR(36) PRIMARY KEY, "checksum" VARCHAR(64) NOT NULL, "finished_at" TIMESTAMPTZ,
            "migration_name" VARCHAR(255) NOT NULL, "logs" TEXT, "rolled_back_at" TIMESTAMPTZ,
            "started_at" TIMESTAMPTZ NOT NULL DEFAULT now(), "applied_steps_count" INTEGER NOT NULL DEFAULT 0)""");
      for (String migration : List.of("20260812220338_init", "20260812221000_add_refresh_tokens",
          "20260812223000_search_history_coords")) {
        statement.execute(resource("/prisma-migrations/" + migration + ".sql"));
        statement.execute("INSERT INTO \"_prisma_migrations\" (\"id\", \"checksum\", \"migration_name\", "
            + "\"finished_at\", \"applied_steps_count\") VALUES (gen_random_uuid(), 'x', '" + migration + "', now(), 1)");
      }

      String tomorrow = StubUpstreams.today().plusDays(1).toString();
      statement.execute("""
          INSERT INTO "users" ("id", "email", "name", "avatarUrl", "passwordHash", "createdAt", "updatedAt")
          VALUES ('%s', '%s', 'Legacy User', NULL, '%s', '2026-08-12 22:10:00.123', '2026-08-13 09:00:00.456');
          INSERT INTO "user_settings" ("id", "userId", "theme", "language", "temperatureUnit", "updatedAt")
          VALUES ('cm0legacysettings00000001', '%s', 'LIGHT', 'ka', 'FAHRENHEIT', '2026-08-12 22:10:00.123');
          INSERT INTO "favorites" ("id", "userId", "locationId", "locationName", "country", "latitude", "longitude",
            "isPinned", "createdAt", "updatedAt")
          VALUES ('cm0legacyfavorite00000001', '%s', 'tbilisi', 'Tbilisi', 'Georgia', 41.7151, 44.8271, true,
            '2026-08-12 22:10:00.123', '2026-08-12 22:10:00.123');
          INSERT INTO "search_history" ("id", "userId", "query", "searchedAt", "latitude", "longitude")
          VALUES ('cm0legacysearch0000000001', '%s', 'Batumi', '2026-08-12 22:11:00.000', 41.6168, 41.6367);
          INSERT INTO "notifications" ("id", "userId", "title", "body", "type", "read", "metadata", "createdAt", "updatedAt")
          VALUES ('cm0legacynotification0001', '%s', 'Rain Alert', 'Legacy rain alert', 'ALERT', false,
            '{"category":"rain","dedupeKey":"rain:%s:Legacy","location":"Legacy","area":"Legacy"}'::jsonb,
            '2026-08-12 22:12:00.000', '2026-08-12 22:12:00.000');
          INSERT INTO "refresh_tokens" ("id", "userId", "tokenHash", "expiresAt", "createdAt")
          VALUES ('%s', '%s', '%s', '2126-01-01 00:00:00.000', '2026-08-12 22:10:00.123');
          """.formatted(USER_ID, EMAIL, BCRYPTJS_HASH, USER_ID, USER_ID, USER_ID, USER_ID, tomorrow,
          REFRESH_JTI, USER_ID, JwtService.hashToken(NODE_REFRESH_TOKEN)));
    } catch (SQLException exception) {
      throw new IllegalStateException(exception);
    }
  }

  @Test
  void flywayBaselinesTheExistingSchemaWithoutRunningMigrations() throws SQLException {
    try (Connection connection = connect(); Statement statement = connection.createStatement()) {
      ResultSet history = statement.executeQuery(
          "SELECT \"version\", \"type\", \"success\" FROM \"flyway_schema_history\" ORDER BY \"installed_rank\"");
      assertThat(history.next()).isTrue();
      assertThat(history.getString("version")).isEqualTo("1");
      assertThat(history.getString("type")).isEqualTo("BASELINE");
      assertThat(history.getBoolean("success")).isTrue();
      assertThat(history.next()).isFalse();

      assertThat(count(statement, "_prisma_migrations")).isEqualTo(3);
      assertThat(count(statement, "users")).isGreaterThanOrEqualTo(1);
    }
  }

  @Test
  void legacyBcryptjsPasswordStillLogsIn() {
    Result login = api.post("/api/v1/auth/login", Map.of("email", EMAIL, "password", "Password123!"), null);

    assertThat(login.status()).isEqualTo(200);
    assertThat(login.json("data.user.id")).isEqualTo(USER_ID);
    assertThat(login.json("data.user.createdAt")).isEqualTo("2026-08-12T22:10:00.123Z");
    assertThat(login.json("data.user.settings.theme")).isEqualTo("LIGHT");
    assertThat(login.json("data.user.settings.language")).isEqualTo("ka");

    Result wrong = api.post("/api/v1/auth/login", Map.of("email", EMAIL, "password", "Password123"), null);
    assertThat(wrong.status()).isEqualTo(401);
  }

  @Test
  void accessTokensIssuedByNodeAreAccepted() {
    Result profile = api.get("/api/v1/auth/profile", NODE_ACCESS_TOKEN);
    assertThat(profile.status()).isEqualTo(200);
    assertThat(profile.json("data.email")).isEqualTo(EMAIL);
    assertThat(profile.json("data.updatedAt")).isEqualTo("2026-08-13T09:00:00.456Z");

    Result expired = api.get("/api/v1/auth/profile", NODE_EXPIRED_ACCESS_TOKEN);
    assertThat(expired.status()).isEqualTo(401);
    assertThat(expired.errorCode()).isEqualTo("INVALID_ACCESS_TOKEN");
  }

  @Test
  void existingUserDataIsReturnedUnchanged() {
    Result favorites = api.get("/api/v1/favorites/me", NODE_ACCESS_TOKEN);
    assertThat(favorites.json("data.0.id")).isEqualTo("cm0legacyfavorite00000001");
    assertThat(favorites.json("data.0.isPinned")).isEqualTo(true);
    assertThat(favorites.json("data.0.latitude")).isEqualTo(41.7151);

    Result history = api.get("/api/v1/search-history/me", NODE_ACCESS_TOKEN);
    assertThat(history.json("data.0.query")).isEqualTo("Batumi");
    assertThat(history.json("data.0.searchedAt")).isEqualTo("2026-08-12T22:11:00.000Z");

    Result notifications = api.get("/api/v1/notifications/me", NODE_ACCESS_TOKEN);
    Map<?, ?> legacy = ((List<?>) notifications.json("data")).stream()
        .map(item -> (Map<?, ?>) item)
        .filter(item -> "cm0legacynotification0001".equals(item.get("id")))
        .findFirst().orElseThrow();
    assertThat(((Map<?, ?>) legacy.get("metadata")).get("category")).isEqualTo("rain");
    assertThat(legacy.get("type")).isEqualTo("ALERT");
    assertThat(legacy.get("createdAt")).isEqualTo("2026-08-12T22:12:00.000Z");
  }

  @Test
  void syncDeduplicatesAgainstNotificationsCreatedByNode() {
    Result sync = api.post("/api/v1/notifications/me/sync?location=Legacy", null, NODE_ACCESS_TOKEN);

    assertThat(sync.status()).isEqualTo(200);
    assertThat(sync.json("data.createdCount")).isEqualTo(2);
    assertThat(sync.body().split("\"category\":\"rain\"", -1)).hasSize(2);
  }

  @Test
  void refreshTokenIssuedByNodeRotatesOnce() throws SQLException {
    Result refresh = api.post("/api/v1/auth/refresh", Map.of("refreshToken", NODE_REFRESH_TOKEN), null);
    assertThat(refresh.status()).isEqualTo(200);
    assertThat(refresh.json("data.user.id")).isEqualTo(USER_ID);

    try (Connection connection = connect(); Statement statement = connection.createStatement()) {
      ResultSet row = statement.executeQuery(
          "SELECT \"revokedAt\" FROM \"refresh_tokens\" WHERE \"id\" = '" + REFRESH_JTI + "'");
      assertThat(row.next()).isTrue();
      assertThat(row.getTimestamp("revokedAt")).isNotNull();
    }

    Result reuse = api.post("/api/v1/auth/refresh", Map.of("refreshToken", NODE_REFRESH_TOKEN), null);
    assertThat(reuse.status()).isEqualTo(401);
  }

  private static long count(Statement statement, String table) throws SQLException {
    ResultSet result = statement.executeQuery("SELECT count(*) FROM \"" + table + "\"");
    result.next();
    return result.getLong(1);
  }

  private static Connection connect() throws SQLException {
    return DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
  }

  private static String resource(String path) {
    try (InputStream stream = LegacyDatabaseCompatibilityTest.class.getResourceAsStream(path)) {
      if (stream == null) {
        throw new IllegalStateException("Missing test resource " + path);
      }
      return new String(stream.readAllBytes(), StandardCharsets.UTF_8);
    } catch (IOException exception) {
      throw new IllegalStateException(exception);
    }
  }
}
